// ============================================================
// Buyer Universe — Sample set for origination buyer matching
// These are indicative strategic and financial buyers active in
// German Financial Services M&A. For internal origination use only.
// ============================================================

import { BuyerProfile } from "./schema";

export const buyers: BuyerProfile[] = [
  // ── Private Equity ─────────────────────────────────────────
  {
    id: "by-pe01",
    name: "Warburg Pincus",
    website: "warburgpincus.com",
    hqCity: "New York (Germany office: Frankfurt)",
    country: "USA / Germany",
    buyerType: "PE",
    sectorFocus: ["Banking", "Payments", "Asset Management", "Wealth Management"],
    subsectorFocus: ["Fintech", "Payment Service Provider", "Digital Wealth"],
    ticketSizeMin: 200,
    ticketSizeMax: 2000,
    geographicFocus: ["Germany", "DACH", "Western Europe"],
    description: "Major global PE with strong FS sector focus; active in German and European fintech and financial services.",
    strategicRationale: "Strong track record in financial services investments, active in European payments and WM consolidation",
    aum: 83,
    sourceUrl: "https://www.warburgpincus.com",
    confidenceScore: 85,
  },
  {
    id: "by-pe02",
    name: "Advent International",
    website: "adventinternational.com",
    hqCity: "Boston (Germany office: Frankfurt)",
    country: "USA / Germany",
    buyerType: "PE",
    sectorFocus: ["Banking", "Payments"],
    subsectorFocus: ["Commercial Banking", "Payment Service Provider", "Acquirer"],
    ticketSizeMin: 500,
    ticketSizeMax: 5000,
    geographicFocus: ["Germany", "Western Europe"],
    description: "Major global PE firm; previously invested in Aareal Bank (taken private 2022) and payment sector assets.",
    strategicRationale: "Prior Aareal Bank ownership demonstrates comfort with German banking assets; payments track record",
    aum: 58,
    sourceUrl: "https://www.adventinternational.com",
    confidenceScore: 88,
  },
  {
    id: "by-pe03",
    name: "Centerbridge Partners",
    website: "centerbridge.com",
    hqCity: "New York / London",
    country: "USA / UK",
    buyerType: "PE",
    sectorFocus: ["Banking"],
    subsectorFocus: ["Commercial Banking", "Specialized Bank"],
    ticketSizeMin: 300,
    ticketSizeMax: 3000,
    geographicFocus: ["Germany", "Western Europe"],
    description: "Credit and PE firm; co-investor with Advent in Aareal Bank privatization.",
    strategicRationale: "Familiar with German banking regulation and commercial real estate finance assets",
    sourceUrl: "https://www.centerbridge.com",
    confidenceScore: 80,
  },
  {
    id: "by-pe04",
    name: "Montagu Private Equity",
    website: "montagu.com",
    hqCity: "London",
    country: "UK",
    buyerType: "PE",
    sectorFocus: ["Asset Management"],
    subsectorFocus: ["Fund Administration / Master-KVG", "Independent Asset Manager"],
    ticketSizeMin: 200,
    ticketSizeMax: 2000,
    geographicFocus: ["Germany", "Western Europe"],
    description: "European mid-market PE; owns Universal Investment Group — Germany's largest fund administration platform.",
    strategicRationale: "Active platform investor in German AM infrastructure; looking for add-ons to Universal Investment",
    aum: 14,
    sourceUrl: "https://www.montagu.com/portfolio/universal-investment",
    confidenceScore: 90,
  },
  {
    id: "by-pe05",
    name: "Apollo Global Management",
    website: "apollo.com",
    hqCity: "New York (Germany office: Frankfurt/Munich)",
    country: "USA / Germany",
    buyerType: "PE",
    sectorFocus: ["Banking", "Payments"],
    subsectorFocus: ["Regional Bank", "Consumer Finance"],
    ticketSizeMin: 500,
    ticketSizeMax: 10000,
    geographicFocus: ["Germany", "Western Europe"],
    description: "Major global alternative asset manager; led OLB investment consortium.",
    strategicRationale: "OLB ownership shows appetite for German regional banking assets; growing European presence",
    aum: 600,
    sourceUrl: "https://www.apollo.com",
    confidenceScore: 85,
  },
  {
    id: "by-pe06",
    name: "KKR",
    website: "kkr.com",
    hqCity: "New York (Germany office: Frankfurt)",
    country: "USA / Germany",
    buyerType: "PE",
    sectorFocus: ["Payments", "Asset Management"],
    subsectorFocus: ["Payment Service Provider", "Digital Wealth"],
    ticketSizeMin: 500,
    ticketSizeMax: 10000,
    geographicFocus: ["Germany", "DACH", "Western Europe"],
    description: "Global PE; majority shareholder in Unzer GmbH (German PSP).",
    strategicRationale: "Active in German payments; financial services sector knowledge across portfolio",
    aum: 500,
    sourceUrl: "https://www.kkr.com",
    confidenceScore: 87,
  },
  {
    id: "by-pe07",
    name: "Bain Capital",
    website: "baincapital.com",
    hqCity: "Boston (Europe: London/Munich)",
    country: "USA / Europe",
    buyerType: "PE",
    sectorFocus: ["Payments", "Asset Management"],
    subsectorFocus: ["Robo-Advisor / Digital Wealth", "Payment Service Provider"],
    ticketSizeMin: 200,
    ticketSizeMax: 5000,
    geographicFocus: ["Germany", "Western Europe"],
    description: "Global PE; investor in SumUp alongside Goldman Sachs.",
    strategicRationale: "SumUp investment signals German payments interest; broad financial services M&A activity",
    aum: 160,
    sourceUrl: "https://www.baincapital.com",
    confidenceScore: 82,
  },
  {
    id: "by-pe08",
    name: "Permira",
    website: "permira.com",
    hqCity: "London (Germany: Frankfurt)",
    country: "UK / Germany",
    buyerType: "PE",
    sectorFocus: ["Asset Management", "Wealth Management"],
    subsectorFocus: ["Independent Asset Manager", "Independent Wealth Manager"],
    ticketSizeMin: 500,
    ticketSizeMax: 5000,
    geographicFocus: ["Germany", "DACH", "Western Europe"],
    description: "Pan-European PE with growing financial services focus; seeks scalable platforms in AM/WM.",
    strategicRationale: "European AM/WM consolidation play; interested in boutique asset manager platforms",
    aum: 65,
    sourceUrl: "https://www.permira.com",
    confidenceScore: 78,
  },

  // ── Strategic Acquirers ─────────────────────────────────────
  {
    id: "by-st01",
    name: "ABN AMRO Group NV",
    website: "abnamro.com",
    hqCity: "Amsterdam",
    country: "Netherlands",
    buyerType: "Strategic",
    sectorFocus: ["Banking", "Wealth Management"],
    subsectorFocus: ["Private Bank", "Multi-Family Office"],
    ticketSizeMin: 200,
    ticketSizeMax: 3000,
    geographicFocus: ["Germany", "Western Europe"],
    description: "Dutch listed bank; acquired Hauck Aufhäuser Lampe in 2025 to become top-3 German private bank.",
    strategicRationale: "Actively building out German private banking/WM; Bethmann HAL could add further WM bolt-ons",
    sourceUrl: "https://www.abnamro.com/en/news/abn-amro-completes-acquisition-of-hauck-aufhaeuser-lampe-in-germany",
    confidenceScore: 90,
  },
  {
    id: "by-st02",
    name: "Nexi SpA",
    website: "nexigroup.com",
    hqCity: "Milan",
    country: "Italy",
    buyerType: "Strategic",
    sectorFocus: ["Payments"],
    subsectorFocus: ["Acquirer", "Payment Service Provider"],
    ticketSizeMin: 100,
    ticketSizeMax: 2000,
    geographicFocus: ["Germany", "Western Europe"],
    description: "Major European payments company; owns Concardis in Germany.",
    strategicRationale: "Consolidation of German payment infrastructure; potential tuck-in payments acquisitions",
    sourceUrl: "https://www.nexigroup.com",
    confidenceScore: 82,
  },
  {
    id: "by-st03",
    name: "Worldline SA",
    website: "worldline.com",
    hqCity: "Bezons (Paris region)",
    country: "France",
    buyerType: "Strategic",
    sectorFocus: ["Payments"],
    subsectorFocus: ["Acquirer", "Payment Service Provider"],
    ticketSizeMin: 100,
    ticketSizeMax: 2000,
    geographicFocus: ["Germany", "Western Europe"],
    description: "European payments leader; majority shareholder in PAYONE; German subsidiary also operates directly.",
    strategicRationale: "German footprint via PAYONE; limited near-term appetite given restructuring in 2024-25",
    sourceUrl: "https://www.worldline.com",
    confidenceScore: 75,
  },
  {
    id: "by-st04",
    name: "DWS Group (potential acquirer in AM consolidation)",
    website: "dws.com",
    hqCity: "Frankfurt am Main",
    country: "Germany",
    buyerType: "Strategic",
    sectorFocus: ["Asset Management"],
    subsectorFocus: ["Independent Asset Manager", "Fund Boutique / KVG"],
    ticketSizeMin: 50,
    ticketSizeMax: 500,
    geographicFocus: ["Germany", "Western Europe"],
    description: "Germany's largest asset manager; could acquire boutique AM firms to fill capability gaps.",
    strategicRationale: "Active/alternatives gap-filling; boutique AM consolidation candidate in Germany",
    sourceUrl: "https://www.dws.com",
    confidenceScore: 80,
  },
  {
    id: "by-st05",
    name: "Natixis Investment Managers",
    website: "im.natixis.com",
    hqCity: "Paris",
    country: "France",
    buyerType: "Strategic",
    sectorFocus: ["Asset Management"],
    subsectorFocus: ["Independent Asset Manager", "Fund Boutique / KVG"],
    ticketSizeMin: 100,
    ticketSizeMax: 1000,
    geographicFocus: ["Germany", "Western Europe"],
    description: "Multi-boutique AM platform with strong European franchise; actively acquires boutique managers.",
    strategicRationale: "Multi-boutique model suits German boutique AM acquisitions; established DACH distribution",
    sourceUrl: "https://www.im.natixis.com",
    confidenceScore: 80,
  },
  {
    id: "by-st06",
    name: "Amundi Asset Management",
    website: "amundi.com",
    hqCity: "Paris",
    country: "France",
    buyerType: "Strategic",
    sectorFocus: ["Asset Management"],
    subsectorFocus: ["Fund Administration / Master-KVG", "Institutional Multi-Asset"],
    ticketSizeMin: 200,
    ticketSizeMax: 2000,
    geographicFocus: ["Germany", "DACH", "Western Europe"],
    description: "Europe's largest asset manager; consolidation-minded; active acquirer of AM platforms.",
    strategicRationale: "European AM consolidation leader; could acquire German boutiques or administration platforms",
    sourceUrl: "https://www.amundi.com",
    confidenceScore: 82,
  },
  {
    id: "by-st06b",
    name: "Affiliated Managers Group (AMG)",
    website: "amg.com",
    hqCity: "West Palm Beach (Europe: London)",
    country: "USA / UK",
    buyerType: "Strategic",
    sectorFocus: ["Asset Management", "Wealth Management"],
    subsectorFocus: ["Independent Asset Manager", "Fund Boutique / KVG"],
    ticketSizeMin: 50,
    ticketSizeMax: 500,
    geographicFocus: ["Germany", "Western Europe"],
    description: "US asset management holding company with minority stakes in independent managers globally.",
    strategicRationale: "Minority-stake model suits founder-led German AM boutiques; MainFirst already in portfolio",
    sourceUrl: "https://www.amg.com",
    confidenceScore: 78,
  },
  {
    id: "by-st07",
    name: "Global Payments Inc.",
    website: "globalpayments.com",
    hqCity: "Atlanta (Germany office: Hamburg)",
    country: "USA / Germany",
    buyerType: "Strategic",
    sectorFocus: ["Payments"],
    subsectorFocus: ["Acquirer", "Payment Service Provider", "Merchant Solutions"],
    ticketSizeMin: 200,
    ticketSizeMax: 5000,
    geographicFocus: ["Germany", "Western Europe"],
    description: "Large US payments company; owns EVO Payments Germany.",
    strategicRationale: "German footprint via EVO; could acquire additional German payment assets",
    sourceUrl: "https://www.globalpayments.com",
    confidenceScore: 75,
  },

  // ── Family Offices / Long-term Capital ─────────────────────
  {
    id: "by-fo01",
    name: "Bertelsmann SE & Co. KGaA (via Bertelsmann Investments)",
    website: "bertelsmann.com",
    hqCity: "Gütersloh",
    country: "Germany",
    buyerType: "Strategic",
    sectorFocus: ["Payments", "Wealth Management"],
    subsectorFocus: ["BNPL / Invoice Finance", "Digital Wealth"],
    ticketSizeMin: 50,
    ticketSizeMax: 1000,
    geographicFocus: ["Germany", "Western Europe"],
    description: "German media and services conglomerate; owns Riverty (payments/BNPL); may also divest FS assets.",
    strategicRationale: "Could either acquire FS add-ons or divest Riverty — dual buyer/seller perspective",
    sourceUrl: "https://www.bertelsmann.com",
    confidenceScore: 78,
  },
];

// ── Matching helpers ─────────────────────────────────────────

export function getBuyersForSector(sector: string): BuyerProfile[] {
  return buyers.filter((b) => b.sectorFocus.includes(sector as never));
}

export function getBuyerById(id: string): BuyerProfile | undefined {
  return buyers.find((b) => b.id === id);
}

/**
 * Returns top buyers for a given company target based on sector/subsector fit.
 * This is a simple heuristic — not a formal sell-side process.
 */
export function matchBuyers(
  sector: string,
  subsector: string,
  sizeBucketFit: "nano" | "micro" | "small" | "mid" | "large" | "mega",
  ownershipType: string
): BuyerProfile[] {
  const sectorMatch = buyers.filter((b) =>
    b.sectorFocus.includes(sector as never)
  );

  // Prefer PE buyers for PE-ready ownership types
  const peReady = ["founder-owned", "partner-owned", "family-owned", "PE-backed", "VC-backed"];
  if (peReady.includes(ownershipType)) {
    return sectorMatch.sort((a, b) => {
      const aPE = a.buyerType === "PE" ? 1 : 0;
      const bPE = b.buyerType === "PE" ? 1 : 0;
      return bPE - aPE;
    });
  }

  return sectorMatch;
}
