import { Company, Contact, Deal, Tag } from "./types";

export const tags: Tag[] = [
  { id: "t1", name: "SaaS", color: "#6366f1" },
  { id: "t2", name: "HealthTech", color: "#10b981" },
  { id: "t3", name: "FinTech", color: "#f59e0b" },
  { id: "t4", name: "PE-Backed", color: "#8b5cf6" },
  { id: "t5", name: "Family Office", color: "#ec4899" },
  { id: "t6", name: "Founder-led", color: "#14b8a6" },
  { id: "t7", name: "B2B", color: "#3b82f6" },
  { id: "t8", name: "High Growth", color: "#f97316" },
  { id: "t9", name: "Profitable", color: "#22c55e" },
  { id: "t10", name: "Platform", color: "#a855f7" },
];

export const contacts: Contact[] = [
  {
    id: "c1",
    name: "Alice Bauer",
    title: "CEO",
    email: "a.bauer@nexalytics.com",
    phone: "+49 30 12345678",
    companyId: "co1",
    isPrimary: true,
  },
  {
    id: "c2",
    name: "Marcus Klein",
    title: "CFO",
    email: "m.klein@nexalytics.com",
    companyId: "co1",
    isPrimary: false,
  },
  {
    id: "c3",
    name: "Sophie Hartmann",
    title: "Founder & CEO",
    email: "s.hartmann@medloop.io",
    phone: "+41 44 9876543",
    companyId: "co2",
    isPrimary: true,
  },
  {
    id: "c4",
    name: "Tomáš Novák",
    title: "Managing Director",
    email: "t.novak@payflux.eu",
    companyId: "co3",
    isPrimary: true,
  },
  {
    id: "c5",
    name: "Ingrid Svensson",
    title: "CEO",
    email: "i.svensson@logisense.se",
    phone: "+46 8 55512345",
    companyId: "co4",
    isPrimary: true,
  },
  {
    id: "c6",
    name: "Ralf Müller",
    title: "Partner",
    email: "r.mueller@nordkapital.com",
    companyId: "co11",
    isPrimary: true,
  },
  {
    id: "c7",
    name: "Claire Dubois",
    title: "Investment Director",
    email: "c.dubois@atlaspe.fr",
    companyId: "co12",
    isPrimary: true,
  },
  {
    id: "c8",
    name: "James Whitfield",
    title: "Principal",
    email: "j.whitfield@oakbridge.co.uk",
    companyId: "co13",
    isPrimary: true,
  },
];

export const companies: Company[] = [
  // TARGETS (co1–co10)
  {
    id: "co1",
    name: "Nexalytics GmbH",
    type: "target",
    sector: "Technology",
    subsector: "B2B Analytics SaaS",
    hq: "Berlin",
    country: "Germany",
    revenue: 8.2,
    ebitda: 2.1,
    employees: 65,
    website: "nexalytics.com",
    status: "in_discussion",
    priority: "high",
    priorityScore: 87,
    description:
      "B2B analytics platform for mid-market manufacturers with 120+ enterprise clients.",
    notes:
      "CEO is open to strategic conversations. CTO leaving in Q2 — potential urgency.",
    tags: ["t1", "t7", "t9"],
    contacts: ["c1", "c2"],
    watchlisted: true,
    createdAt: "2025-11-01",
    updatedAt: "2026-02-10",
    ownershipType: "Founder-led",
    founded: 2017,
    source: "Industry conference",
  },
  {
    id: "co2",
    name: "Medloop AG",
    type: "target",
    sector: "Healthcare",
    subsector: "Clinical Workflow SaaS",
    hq: "Zurich",
    country: "Switzerland",
    revenue: 5.4,
    ebitda: 0.8,
    employees: 42,
    website: "medloop.io",
    status: "outreach_pending",
    priority: "high",
    priorityScore: 82,
    description:
      "Digital clinical workflow platform used by 60 Swiss and German hospital networks.",
    notes: "Series B closed 18 months ago. Investors likely looking for exit.",
    tags: ["t2", "t1", "t8"],
    contacts: ["c3"],
    watchlisted: true,
    createdAt: "2025-12-03",
    updatedAt: "2026-01-22",
    ownershipType: "VC-backed",
    founded: 2019,
    source: "VC portfolio scan",
  },
  {
    id: "co3",
    name: "PayFlux s.r.o.",
    type: "target",
    sector: "Financial Services",
    subsector: "B2B Payments",
    hq: "Prague",
    country: "Czech Republic",
    revenue: 12.7,
    ebitda: 3.9,
    employees: 88,
    website: "payflux.eu",
    status: "active",
    priority: "medium",
    priorityScore: 71,
    description:
      "Cross-border B2B payment infrastructure for Central & Eastern European SMEs.",
    notes: "Strong recurring revenue. Competitive pressure from Stripe Treasury.",
    tags: ["t3", "t7", "t9"],
    contacts: ["c4"],
    watchlisted: false,
    createdAt: "2025-10-15",
    updatedAt: "2026-03-01",
    ownershipType: "PE-backed",
    founded: 2015,
    source: "Direct referral",
  },
  {
    id: "co4",
    name: "LogiSense AB",
    type: "target",
    sector: "Logistics & Supply Chain",
    subsector: "Freight Tech",
    hq: "Stockholm",
    country: "Sweden",
    revenue: 18.5,
    ebitda: 4.2,
    employees: 134,
    website: "logisense.se",
    status: "active",
    priority: "medium",
    priorityScore: 68,
    description:
      "AI-powered freight optimization platform serving Nordic 3PLs and shippers.",
    notes: "Founder approaching retirement age. Succession planning conversation initiated.",
    tags: ["t7", "t9", "t6"],
    contacts: ["c5"],
    watchlisted: false,
    createdAt: "2026-01-10",
    updatedAt: "2026-02-28",
    ownershipType: "Founder-led",
    founded: 2012,
    source: "Cold outreach",
  },
  {
    id: "co5",
    name: "Costruttivo Srl",
    type: "target",
    sector: "Construction Tech",
    subsector: "Project Management SaaS",
    hq: "Milan",
    country: "Italy",
    revenue: 6.1,
    ebitda: 1.4,
    employees: 51,
    website: "costruttivo.it",
    status: "watchlist",
    priority: "medium",
    priorityScore: 59,
    description:
      "SaaS platform for construction project management with strong Italian market penetration.",
    notes: "Awaiting Q1 results. Revenue growth slowing — may lower valuation expectations.",
    tags: ["t1", "t7"],
    contacts: [],
    watchlisted: true,
    createdAt: "2025-09-20",
    updatedAt: "2026-01-15",
    ownershipType: "Family-owned",
    founded: 2016,
    source: "M&A advisor",
  },
  {
    id: "co6",
    name: "DataBridge BV",
    type: "target",
    sector: "Technology",
    subsector: "Data Integration",
    hq: "Amsterdam",
    country: "Netherlands",
    revenue: 9.8,
    ebitda: 2.8,
    employees: 72,
    website: "databridge.nl",
    status: "active",
    priority: "high",
    priorityScore: 79,
    description:
      "No-code data integration platform with 200+ connectors for mid-market enterprises.",
    notes:
      "Strategic fit with buyer co12 very strong. Fast-track to LOI possible.",
    tags: ["t1", "t7", "t8"],
    contacts: [],
    watchlisted: true,
    createdAt: "2026-01-05",
    updatedAt: "2026-03-10",
    ownershipType: "VC-backed",
    founded: 2018,
    source: "Industry report",
  },
  {
    id: "co7",
    name: "Recurra SAS",
    type: "target",
    sector: "Financial Services",
    subsector: "Subscription Billing",
    hq: "Paris",
    country: "France",
    revenue: 4.3,
    ebitda: 0.6,
    employees: 38,
    website: "recurra.fr",
    status: "outreach_pending",
    priority: "low",
    priorityScore: 44,
    description:
      "Subscription billing and revenue recognition platform for SaaS companies.",
    notes: "Small team. High NRR (118%). Limited sales capacity.",
    tags: ["t3", "t1"],
    contacts: [],
    watchlisted: false,
    createdAt: "2026-02-01",
    updatedAt: "2026-02-28",
    ownershipType: "Bootstrapped",
    founded: 2020,
    source: "LinkedIn outreach",
  },
  {
    id: "co8",
    name: "GreenhouseIQ Ltd",
    type: "target",
    sector: "AgriTech",
    subsector: "Precision Agriculture",
    hq: "Dublin",
    country: "Ireland",
    revenue: 3.7,
    ebitda: 0.4,
    employees: 29,
    website: "greenhouseiq.ie",
    status: "watchlist",
    priority: "low",
    priorityScore: 38,
    description:
      "IoT sensor and AI analytics platform for commercial greenhouse operators.",
    notes: "Niche but defensible. Watch for Series A close.",
    tags: ["t8"],
    contacts: [],
    watchlisted: true,
    createdAt: "2026-02-15",
    updatedAt: "2026-03-05",
    ownershipType: "VC-backed",
    founded: 2021,
    source: "VC portfolio scan",
  },
  {
    id: "co9",
    name: "FleetMind OÜ",
    type: "target",
    sector: "Logistics & Supply Chain",
    subsector: "Fleet Management",
    hq: "Tallinn",
    country: "Estonia",
    revenue: 7.6,
    ebitda: 1.9,
    employees: 58,
    website: "fleetmind.ee",
    status: "active",
    priority: "medium",
    priorityScore: 63,
    description:
      "Fleet telematics and compliance platform for European transport companies.",
    notes: "Expanding to Poland and Romania. Strong unit economics.",
    tags: ["t7", "t9", "t8"],
    contacts: [],
    watchlisted: false,
    createdAt: "2025-11-20",
    updatedAt: "2026-02-14",
    ownershipType: "Founder-led",
    founded: 2014,
    source: "Cold outreach",
  },
  {
    id: "co10",
    name: "SkillsPath GmbH",
    type: "target",
    sector: "HRTech",
    subsector: "Learning & Development",
    hq: "Munich",
    country: "Germany",
    revenue: 11.2,
    ebitda: 2.9,
    employees: 95,
    website: "skillspath.de",
    status: "passed",
    priority: "low",
    priorityScore: 31,
    description:
      "Corporate L&D platform with AI-driven skills gap analysis. 300+ enterprise clients.",
    notes: "Valuation expectations too high. Revisit after next funding round.",
    tags: ["t1", "t7"],
    contacts: [],
    watchlisted: false,
    createdAt: "2025-08-10",
    updatedAt: "2025-12-20",
    ownershipType: "PE-backed",
    founded: 2013,
    source: "M&A advisor",
  },

  // BUYERS / INVESTORS (co11–co20)
  {
    id: "co11",
    name: "NordKapital Partners",
    type: "buyer",
    sector: "Private Equity",
    subsector: "Mid-Market Buyouts",
    hq: "Hamburg",
    country: "Germany",
    revenue: undefined,
    ebitda: undefined,
    employees: 28,
    website: "nordkapital.com",
    status: "active",
    priority: "high",
    priorityScore: 91,
    description:
      "Mid-market PE fund targeting B2B SaaS and tech-enabled services in DACH region. AUM €600M.",
    notes:
      "Actively deploying from Fund IV. Looking for €10-50M EV targets. Strong operational support.",
    tags: ["t4", "t1", "t7"],
    contacts: ["c6"],
    watchlisted: false,
    createdAt: "2025-09-01",
    updatedAt: "2026-03-10",
    ownershipType: "Independent",
    source: "Direct relationship",
  },
  {
    id: "co12",
    name: "Atlas PE",
    type: "buyer",
    sector: "Private Equity",
    subsector: "Growth Buyouts",
    hq: "Paris",
    country: "France",
    revenue: undefined,
    ebitda: undefined,
    employees: 45,
    website: "atlaspe.fr",
    status: "active",
    priority: "high",
    priorityScore: 85,
    description:
      "Pan-European growth buyout fund focused on B2B SaaS and digital infrastructure. AUM €1.2B.",
    notes: "Mandate includes data/analytics platform acquisitions. DataBridge is a strong fit.",
    tags: ["t4", "t1"],
    contacts: ["c7"],
    watchlisted: false,
    createdAt: "2025-10-05",
    updatedAt: "2026-02-20",
    ownershipType: "Independent",
    source: "Conference",
  },
  {
    id: "co13",
    name: "Oakbridge Capital",
    type: "buyer",
    sector: "Private Equity",
    subsector: "Lower Mid-Market",
    hq: "London",
    country: "United Kingdom",
    revenue: undefined,
    ebitda: undefined,
    employees: 22,
    website: "oakbridge.co.uk",
    status: "active",
    priority: "medium",
    priorityScore: 74,
    description:
      "Lower mid-market buyout fund. Sector-agnostic with preference for profitable bootstrapped businesses.",
    notes: "Flexible on structure. Have done carve-outs and MBOs.",
    tags: ["t4"],
    contacts: ["c8"],
    watchlisted: false,
    createdAt: "2025-11-15",
    updatedAt: "2026-01-30",
    ownershipType: "Independent",
    source: "Referral",
  },
  {
    id: "co14",
    name: "Meridian Growth Fund",
    type: "investor",
    sector: "Venture Capital",
    subsector: "Series B/C",
    hq: "Stockholm",
    country: "Sweden",
    revenue: undefined,
    ebitda: undefined,
    employees: 18,
    website: "meridiangrowth.se",
    status: "active",
    priority: "medium",
    priorityScore: 66,
    description:
      "Nordic growth equity fund. Focus on B2B SaaS €3-15M ARR range. AUM €250M.",
    notes: "Looking for co-investment opportunities alongside buyout funds.",
    tags: ["t4", "t1", "t8"],
    contacts: [],
    watchlisted: false,
    createdAt: "2025-12-01",
    updatedAt: "2026-02-05",
    ownershipType: "Independent",
    source: "Industry network",
  },
  {
    id: "co15",
    name: "Helios Industrial Partners",
    type: "buyer",
    sector: "Private Equity",
    subsector: "Industrial & Manufacturing",
    hq: "Düsseldorf",
    country: "Germany",
    revenue: undefined,
    ebitda: undefined,
    employees: 35,
    website: "heliosindustrial.de",
    status: "active",
    priority: "medium",
    priorityScore: 61,
    description:
      "PE fund focused on industrial technology and manufacturing software. AUM €800M.",
    notes: "Recently exited a logistics software platform. Actively looking for next platform.",
    tags: ["t4", "t7"],
    contacts: [],
    watchlisted: false,
    createdAt: "2026-01-08",
    updatedAt: "2026-03-01",
    ownershipType: "Independent",
    source: "Conference",
  },
  {
    id: "co16",
    name: "Ventus Capital",
    type: "investor",
    sector: "Family Office",
    subsector: "Direct Investments",
    hq: "Zurich",
    country: "Switzerland",
    revenue: undefined,
    ebitda: undefined,
    employees: 9,
    website: "ventuscapital.ch",
    status: "active",
    priority: "low",
    priorityScore: 48,
    description:
      "Swiss family office making direct minority and majority investments in tech companies.",
    notes: "Patient capital. Long hold periods. Interested in HealthTech.",
    tags: ["t5", "t2"],
    contacts: [],
    watchlisted: false,
    createdAt: "2026-01-20",
    updatedAt: "2026-02-28",
    ownershipType: "Family Office",
    source: "Direct referral",
  },
  {
    id: "co17",
    name: "Cascade Equity",
    type: "buyer",
    sector: "Private Equity",
    subsector: "Sector-Focused",
    hq: "Copenhagen",
    country: "Denmark",
    revenue: undefined,
    ebitda: undefined,
    employees: 20,
    website: "cascadeequity.dk",
    status: "active",
    priority: "medium",
    priorityScore: 70,
    description:
      "Nordic-focused PE firm specializing in FinTech and financial services technology.",
    notes: "Very active in CEE expansion plays. PayFlux could be a fit.",
    tags: ["t4", "t3"],
    contacts: [],
    watchlisted: false,
    createdAt: "2025-10-25",
    updatedAt: "2026-02-15",
    ownershipType: "Independent",
    source: "Industry conference",
  },
  {
    id: "co18",
    name: "Foresta Ventures",
    type: "investor",
    sector: "Venture Capital",
    subsector: "Climate & AgriTech",
    hq: "Amsterdam",
    country: "Netherlands",
    revenue: undefined,
    ebitda: undefined,
    employees: 14,
    website: "forestaventures.nl",
    status: "active",
    priority: "low",
    priorityScore: 42,
    description:
      "Climate-focused VC investing in AgriTech and sustainability. AUM €180M.",
    notes: "GreenhouseIQ is a perfect fit. Introductions possible.",
    tags: ["t8"],
    contacts: [],
    watchlisted: false,
    createdAt: "2026-02-10",
    updatedAt: "2026-03-05",
    ownershipType: "Independent",
    source: "LinkedIn",
  },
  {
    id: "co19",
    name: "Alpinum Partners",
    type: "buyer",
    sector: "Private Equity",
    subsector: "Healthcare & Life Sciences",
    hq: "Munich",
    country: "Germany",
    revenue: undefined,
    ebitda: undefined,
    employees: 32,
    website: "alpinumpartners.de",
    status: "active",
    priority: "high",
    priorityScore: 80,
    description:
      "Healthcare-focused PE fund investing across DACH and Benelux. AUM €950M.",
    notes: "Actively looking for HealthTech platforms. Medloop is on their radar too.",
    tags: ["t4", "t2"],
    contacts: [],
    watchlisted: false,
    createdAt: "2025-11-10",
    updatedAt: "2026-03-12",
    ownershipType: "Independent",
    source: "Warm intro",
  },
  {
    id: "co20",
    name: "Delta Horizon Capital",
    type: "buyer",
    sector: "Private Equity",
    subsector: "Buy-and-Build",
    hq: "Brussels",
    country: "Belgium",
    revenue: undefined,
    ebitda: undefined,
    employees: 26,
    website: "deltahorizon.be",
    status: "active",
    priority: "medium",
    priorityScore: 67,
    description:
      "Buy-and-build focused PE firm executing platform strategies in SaaS and HRTech.",
    notes: "Looking for add-on acquisitions under existing HRTech platform.",
    tags: ["t4", "t1", "t10"],
    contacts: [],
    watchlisted: false,
    createdAt: "2026-01-25",
    updatedAt: "2026-03-08",
    ownershipType: "Independent",
    source: "M&A advisor",
  },
];

export const deals: Deal[] = [
  {
    id: "d1",
    name: "NordKapital / Nexalytics",
    targetId: "co1",
    buyerId: "co11",
    status: "due_diligence",
    priority: "high",
    priorityScore: 92,
    evRevMultiple: 4.8,
    evEbitdaMultiple: 18.7,
    estimatedEV: 39.4,
    estimatedRevenue: 8.2,
    estimatedEbitda: 2.1,
    sector: "Technology",
    dealType: "Majority Buyout",
    notes:
      "Management retained. Financial DD underway. Legal review starts April 1. IC memo scheduled for April 15.",
    source: "Proprietary",
    confidence: "confirmed",
    watchlisted: true,
    createdAt: "2025-11-01",
    updatedAt: "2026-03-12",
    tags: ["t1", "t4"],
  },
  {
    id: "d2",
    name: "Alpinum / Medloop",
    targetId: "co2",
    buyerId: "co19",
    status: "loi_submitted",
    priority: "high",
    priorityScore: 85,
    evRevMultiple: 5.5,
    evEbitdaMultiple: 37.5,
    estimatedEV: 29.7,
    estimatedRevenue: 5.4,
    estimatedEbitda: 0.8,
    sector: "Healthcare",
    dealType: "Majority Buyout",
    notes:
      "LOI submitted Feb 28. Exclusivity requested for 45 days. Founders want full exit.",
    source: "Warm intro",
    confidence: "confirmed",
    watchlisted: true,
    createdAt: "2025-12-03",
    updatedAt: "2026-03-01",
    tags: ["t2", "t4"],
  },
  {
    id: "d3",
    name: "Atlas PE / DataBridge",
    targetId: "co6",
    buyerId: "co12",
    status: "negotiation",
    priority: "high",
    priorityScore: 88,
    evRevMultiple: 4.2,
    evEbitdaMultiple: 14.6,
    estimatedEV: 41.2,
    estimatedRevenue: 9.8,
    estimatedEbitda: 2.8,
    sector: "Technology",
    dealType: "Growth Buyout",
    notes:
      "SPA under negotiation. Earn-out structure being finalized. Closing target Q2 2026.",
    source: "Proprietary",
    confidence: "confirmed",
    watchlisted: true,
    createdAt: "2026-01-05",
    updatedAt: "2026-03-14",
    tags: ["t1", "t4"],
  },
  {
    id: "d4",
    name: "Cascade / PayFlux",
    targetId: "co3",
    buyerId: "co17",
    status: "nda_signed",
    priority: "medium",
    priorityScore: 72,
    evRevMultiple: 3.1,
    evEbitdaMultiple: 10.1,
    estimatedEV: 39.4,
    estimatedRevenue: 12.7,
    estimatedEbitda: 3.9,
    sector: "Financial Services",
    dealType: "Majority Buyout",
    notes:
      "NDA signed Feb 10. Management presentation scheduled for March 25. CFO model received.",
    source: "Direct referral",
    confidence: "likely",
    watchlisted: false,
    createdAt: "2025-10-15",
    updatedAt: "2026-02-20",
    tags: ["t3", "t4"],
  },
  {
    id: "d5",
    name: "Helios / LogiSense",
    targetId: "co4",
    buyerId: "co15",
    status: "first_contact",
    priority: "medium",
    priorityScore: 65,
    evRevMultiple: 2.8,
    evEbitdaMultiple: 12.3,
    estimatedEV: 51.8,
    estimatedRevenue: 18.5,
    estimatedEbitda: 4.2,
    sector: "Logistics & Supply Chain",
    dealType: "Buyout",
    notes:
      "Intro call done March 5. Founder interested but wants to explore valuation range first.",
    source: "Cold outreach",
    confidence: "likely",
    watchlisted: false,
    createdAt: "2026-01-10",
    updatedAt: "2026-03-06",
    tags: ["t7"],
  },
  {
    id: "d6",
    name: "NordKapital / SkillsPath",
    targetId: "co10",
    buyerId: "co11",
    status: "closed_lost",
    priority: "low",
    priorityScore: 22,
    evRevMultiple: 5.2,
    evEbitdaMultiple: 20.1,
    estimatedEV: 58.2,
    estimatedRevenue: 11.2,
    estimatedEbitda: 2.9,
    sector: "HRTech",
    dealType: "Majority Buyout",
    notes:
      "Passed — valuation gap too large. Seller wanted 6x revenue. Will revisit post-2027 refinancing.",
    source: "M&A advisor",
    confidence: "confirmed",
    watchlisted: false,
    closedAt: "2025-12-20",
    createdAt: "2025-08-10",
    updatedAt: "2025-12-20",
    tags: ["t1"],
  },
  {
    id: "d7",
    name: "Delta Horizon / SkillsPath",
    targetId: "co10",
    buyerId: "co20",
    status: "screening",
    priority: "low",
    priorityScore: 34,
    evRevMultiple: 4.5,
    evEbitdaMultiple: 17.4,
    estimatedEV: 50.4,
    estimatedRevenue: 11.2,
    estimatedEbitda: 2.9,
    sector: "HRTech",
    dealType: "Add-on Acquisition",
    notes:
      "Flagged as potential add-on for Delta HRTech platform. Need to assess cultural fit.",
    source: "M&A advisor",
    confidence: "speculative",
    watchlisted: false,
    createdAt: "2026-01-25",
    updatedAt: "2026-02-10",
    tags: ["t1", "t10"],
  },
  {
    id: "d8",
    name: "Oakbridge / FleetMind",
    targetId: "co9",
    buyerId: "co13",
    status: "first_contact",
    priority: "medium",
    priorityScore: 61,
    evRevMultiple: 2.5,
    evEbitdaMultiple: 9.8,
    estimatedEV: 19.0,
    estimatedRevenue: 7.6,
    estimatedEbitda: 1.9,
    sector: "Logistics & Supply Chain",
    dealType: "Majority Buyout",
    notes:
      "First call positive. Founder open to PE backing to fund EU expansion. Follow-up April 2.",
    source: "Referral",
    confidence: "likely",
    watchlisted: false,
    createdAt: "2025-11-20",
    updatedAt: "2026-03-10",
    tags: ["t7", "t4"],
  },
  {
    id: "d9",
    name: "Ventus / Medloop (minority)",
    targetId: "co2",
    buyerId: "co16",
    status: "screening",
    priority: "low",
    priorityScore: 41,
    evRevMultiple: 5.0,
    evEbitdaMultiple: 34.0,
    estimatedEV: 27.0,
    estimatedRevenue: 5.4,
    estimatedEbitda: 0.8,
    sector: "Healthcare",
    dealType: "Minority Stake",
    notes:
      "Ventus interested in 20-30% minority stake if Alpinum deal falls through. Keep as backup.",
    source: "Direct referral",
    confidence: "speculative",
    watchlisted: false,
    createdAt: "2026-01-20",
    updatedAt: "2026-02-14",
    tags: ["t2", "t5"],
  },
  {
    id: "d10",
    name: "Atlas PE / Recurra",
    targetId: "co7",
    buyerId: "co12",
    status: "screening",
    priority: "low",
    priorityScore: 39,
    evRevMultiple: 3.8,
    evEbitdaMultiple: 27.1,
    estimatedEV: 16.3,
    estimatedRevenue: 4.3,
    estimatedEbitda: 0.6,
    sector: "Financial Services",
    dealType: "Buyout",
    notes:
      "Small size may be a challenge for Atlas ticket size. Could be add-on to existing portfolio company.",
    source: "LinkedIn outreach",
    confidence: "speculative",
    watchlisted: false,
    createdAt: "2026-02-01",
    updatedAt: "2026-03-01",
    tags: ["t3", "t1"],
  },
  {
    id: "d11",
    name: "NordKapital / DataBridge",
    targetId: "co6",
    buyerId: "co11",
    status: "closed_lost",
    priority: "low",
    priorityScore: 20,
    evRevMultiple: 3.9,
    evEbitdaMultiple: 13.6,
    estimatedEV: 38.2,
    estimatedRevenue: 9.8,
    estimatedEbitda: 2.8,
    sector: "Technology",
    dealType: "Majority Buyout",
    notes:
      "Lost to Atlas PE on price. NordKapital unwilling to match 4.2x revenue multiple.",
    source: "Proprietary",
    confidence: "confirmed",
    watchlisted: false,
    closedAt: "2026-02-15",
    createdAt: "2026-01-05",
    updatedAt: "2026-02-15",
    tags: ["t1"],
  },
  {
    id: "d12",
    name: "Foresta / GreenhouseIQ",
    targetId: "co8",
    buyerId: "co18",
    status: "screening",
    priority: "low",
    priorityScore: 36,
    evRevMultiple: 4.1,
    evEbitdaMultiple: 38.0,
    estimatedEV: 15.2,
    estimatedRevenue: 3.7,
    estimatedEbitda: 0.4,
    sector: "AgriTech",
    dealType: "Growth Investment",
    notes: "Early stage. Watching for Series A close first. Introductions possible via network.",
    source: "LinkedIn",
    confidence: "speculative",
    watchlisted: true,
    createdAt: "2026-02-10",
    updatedAt: "2026-03-05",
    tags: ["t8"],
  },
  {
    id: "d13",
    name: "Helios / FleetMind",
    targetId: "co9",
    buyerId: "co15",
    status: "first_contact",
    priority: "medium",
    priorityScore: 57,
    evRevMultiple: 2.6,
    evEbitdaMultiple: 10.5,
    estimatedEV: 19.8,
    estimatedRevenue: 7.6,
    estimatedEbitda: 1.9,
    sector: "Logistics & Supply Chain",
    dealType: "Majority Buyout",
    notes:
      "Competing with Oakbridge. Helios has better sector experience but smaller network in Baltics.",
    source: "Cold outreach",
    confidence: "likely",
    watchlisted: false,
    createdAt: "2025-11-20",
    updatedAt: "2026-03-01",
    tags: ["t7"],
  },
  {
    id: "d14",
    name: "Alpinum / Construttivo",
    targetId: "co5",
    buyerId: "co19",
    status: "screening",
    priority: "low",
    priorityScore: 44,
    evRevMultiple: 3.3,
    evEbitdaMultiple: 14.4,
    estimatedEV: 20.1,
    estimatedRevenue: 6.1,
    estimatedEbitda: 1.4,
    sector: "Construction Tech",
    dealType: "Buyout",
    notes:
      "Outside core healthcare mandate but attractive cash flow profile. Reviewing with IC.",
    source: "M&A advisor",
    confidence: "rumor",
    watchlisted: false,
    createdAt: "2025-09-20",
    updatedAt: "2026-01-30",
    tags: ["t1"],
  },
  {
    id: "d15",
    name: "Cascade / PayFlux (bolt-on)",
    targetId: "co3",
    buyerId: "co17",
    status: "closed_won",
    priority: "high",
    priorityScore: 95,
    evRevMultiple: 3.0,
    evEbitdaMultiple: 9.8,
    estimatedEV: 38.1,
    estimatedRevenue: 12.7,
    estimatedEbitda: 3.9,
    sector: "Financial Services",
    dealType: "Bolt-on Acquisition",
    notes:
      "Deal signed March 10. Bolt-on into Cascade's FinTech platform company. Great outcome.",
    source: "Direct referral",
    confidence: "confirmed",
    watchlisted: false,
    closedAt: "2026-03-10",
    createdAt: "2025-10-15",
    updatedAt: "2026-03-10",
    tags: ["t3", "t4"],
  },
];

// Helpers
export function getCompanyById(id: string): Company | undefined {
  return companies.find((c) => c.id === id);
}

export function getDealById(id: string): Deal | undefined {
  return deals.find((d) => d.id === id);
}

export function getContactsByCompanyId(companyId: string): Contact[] {
  return contacts.filter((c) => c.companyId === companyId);
}

export function getTagsByIds(ids: string[]): Tag[] {
  return tags.filter((t) => ids.includes(t.id));
}

export function getTargets(): Company[] {
  return companies.filter((c) => c.type === "target");
}

export function getBuyers(): Company[] {
  return companies.filter((c) => c.type === "buyer" || c.type === "investor");
}

export function getWatchlisted(): Company[] {
  return companies.filter((c) => c.watchlisted);
}

export function getDealsByCompanyId(companyId: string): Deal[] {
  return deals.filter(
    (d) => d.targetId === companyId || d.buyerId === companyId
  );
}
